### ISSUE TITLE
Support SMIE (Emacs 24.4)

### ISSUE THREAD

**Issue by PythonNut** [jscheid/dtrt-indent#14]
Many Emacs 24.4 major modes are now using SMIE, a parser that improves automatic indentation and indentation based navigation. Many minor modes have switched to using it instead of the normal indentation variables, which breaks dtrt-indent in sh-mode for example.

**Comment by rrthomas** [comment]
I believe this now works: `dtrt-indent-find-file-hook` now uses `smie-config-guess` if SMIE is available and the mode supports it. I have tested this with `sh-mode` (for bug #31), but would appreciate some confirmation that it works before I make a new release.

**Comment by jgeerds** [comment]
Thanks @rrthomas ! I've also tested it with sh-mode and it works fine for me.

TBH, I don't understand how `smie` works. Let's take the following file as an example:

```
test_function() {
    if test; then
        echo lol
    fi
}
```
Indentation works fine with your recent changes, but `sh-basic-offset` and `sh-indentation` are set to `2` (and not `4`). I guess `smie` uses a different variable for this. Let's say I want to change the indentation from `4` to `2` and `indent-region` the whole buffer. How can I do that? Changing `sh-indentation`, `sh-basic-offset` and `smie-indent-basic` make no difference.

**Comment by rrthomas** [comment]
Thanks for confirming. Good luck sussing out SMIE; I don't know much about it either.

**Comment by hrehfeld** [comment]
I still run into this, whenever a css-mode file is in the desktop file -- seems related. Reopen?

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  smie-next-sexp(#f(compiled-function () #<bytecode 0xd5cec9>) #f(compiled-function (n) #<bytecode 0x1b0d2f9>) #<subr car> #f(compiled-function (x) "Return the car of the cdr of X." #<bytecode 0x1a49b3>) "}")
  smie-backward-sexp("}")
  smie-indent-keyword()
  run-hook-with-args-until-success(smie-indent-keyword)
  smie-indent-calculate()
  smie-config--get-trace()
  smie-config--guess(1 6439)
  smie-config-guess()
  dtrt-indent-mode(t)
  (lambda nil (dtrt-indent-mode t))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook css-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook css-mode-hook))
  run-mode-hooks(css-mode-hook)
  css-mode()
  set-auto-mode-0(css-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil nil)
  find-file-noselect-1(#<buffer style.css> "style.css" :nowarn nil "style.css" (1738062 66309))
  find-file-noselect("style.css" :nowarn)
  desktop-restore-file-buffer("style.css" "style.css" nil)
  desktop-create-buffer(208 "style.css" "style.css" css-mode nil 1 (nil nil) nil nil ((tab-width . 4) (indent-tabs-mode . t) (buffer-display-time) (buffer-file-coding-system . utf-8-unix)) ((mark-ring nil)))
  eval-buffer(#<buffer  *load*> nil ".desktop" nil t)  ; Reading at buffer position 140676
  load-with-code-conversion(".desktop" ".desktop" t t)
  load(".desktop" t t t)
  desktop-read()
```

**Comment by rrthomas** [comment]
@hrehfeld as far as I can tell, you're experiencing a problem with CSS mode and desktop.el when you have dtrt-indent active? (I made a quick test, of opening a CSS file, quitting Emacs and restarting; the css-mode buffer was loaded fine by desktop.el with no error.) That's not the same as this issue (which was a request for SMIE support), so please file a new issue, with a way to repro and some evidence that the problem is caused by dtrt.

**Comment by hrehfeld** [comment]
Will try, but time is limited atm, currently i'm just not using dtrt-indent on css-mode as a quick workaround.
