### ISSUE TITLE
Mode line info message should be customizable

### ISSUE THREAD

**Issue by IvanMalison** [jscheid/dtrt-indent#19]
The default message "  [dtrt-indent adjusted]" is a bit long for my taste.

**Comment by rrthomas** [comment]
I agree. If you can make a patch with a good shorter message, I'll happily accept it!

**Comment by IvanMalison** [comment]
Why was the closed? The message is still not customizeable.

**Comment by rrthomas** [comment]
Apologies, @IvanMalison, I incorrectly read PR #21 as fixing this. Reopened.
