### ISSUE TITLE
Symbol's value as variable is void: evil-mode

### ISSUE THREAD

**Issue by jackcviers** [jscheid/dtrt-indent#24]
This happens when opening any file. Disabling dtrt-indent removes the error. It appears to be related to the reference in https://github.com/jscheid/dtrt-indent/blob/e029624eebe4c85f3b43452fa4456df1019c2d3f/dtrt-indent.el#L335

Is there any way we can get this list made into a `defcustom`? I, and several users I know, load our packages automatically using a package list that will install a package if it doesn't exist and load it on startup, and this means I have to define a global variable at the top of my user-init-file on startup.

**Comment by andschwa** [comment]
Ah I wondered if that may be an issue. Fixing now.

**Comment by andschwa** [comment]
@jackcviers Can you test that PR? It fixed it for me, but I want to make sure I didn't miss another edge case.
