### ISSUE TITLE
Make a stable release to be included in MELPA stable

### ISSUE THREAD

**Issue by matthewbauer** [jscheid/dtrt-indent#30]
Hi,

I've been using dtrt-indent regularly now and it seems stable. Can you make a versioned release so that it can be included in the MELPA stable set?

**Comment by rrthomas** [comment]
Sure; as far as I can see, I just need a semver-format tag. Can you confirm?

**Comment by matthewbauer** [comment]
Yeah that's what it looks like.

**Comment by rrthomas** [comment]
I made a 0.2.1 release (i.e. the current version). Please can you confirm that it works for MELPA?

**Comment by jgeerds** [comment]
I can verify that the `0.2.1` release from `stable.melpa.org` works fine. Thanks!

**Comment by rrthomas** [comment]
That's great, closing.
