### ISSUE TITLE
Wrong indentation in shell-mode

### ISSUE THREAD

**Issue by jgeerds** [jscheid/dtrt-indent#31]
It seems like dtrt-indent doesn't work very well with shell-mode (bash):

```
test_function() {
    if foo; then
        echo bar
    fi
}
```

dtrt-indent guesses `sh-indentation 4`, which is correct. However, if I call `indent-region` the code indented like this:

```
test_function() {
  if foo; then
      echo bar
  fi
}
```

It looks like a mixed indentation of `2` and `4`. This is probably because `sh-basic-offset` is still set to `2`. Am I missing something? Setting `sh-basic-offset` to the same value like `sh-indentation` fixes the problem. Does it mean there are two different settings which control indentation for shell mode? Is this an upstream "bug"?

Unfortunately, I don't understand the documentation:
```
sh-indentation is a variable defined in ‘sh-script.el’.
Its value is 4

Documentation:
The width for further indentation in Shell-Script mode.
```
```
sh-basic-offset is a variable defined in ‘sh-script.el’.
Its value is 2

Documentation:
The default indentation increment.
This value is used for the ‘+’ and ‘-’ symbols in an indentation variable.
```

There is also a setting if basic offset should be guesses:
```
sh-guess-basic-offset is a compiled Lisp function in ‘sh-script.el’.

(sh-guess-basic-offset VEC)

See if we can determine a reasonable value for ‘sh-basic-offset’.
This is experimental, heuristic and arbitrary!
Argument VEC is a vector of information collected by
‘sh-learn-buffer-indent’.
Return values:
  number          - there appears to be a good single value
  list of numbers - no obvious one, here is a list of one or more
		    reasonable choices
  nil		  - we couldn’t find a reasonable one.

[back]
```

Do we really need dtrt-mode for shell?

**Comment by jgeerds** [comment]
See also https://github.com/jscheid/dtrt-indent/commit/1115688391bf8cc58a814ca99bfc769a3afd46cf

**Comment by jgeerds** [comment]
Whops sorry for the noise. There is alread an open issue addressing my problem: https://github.com/jscheid/dtrt-indent/issues/14

**Comment by rrthomas** [comment]
So, `indent-region` should be calling `smie-indent-line` (as the value of `indent-line-function`).

If I call `indent-line-function`, then indeed it reindents to two spaces. However, the smie code in sh-script.el, as far as I can see, only uses sh-indentation, never sh-basic-offset.

The two spaces seem to be specifically after a brace. This uses `sh-indent-after-open`, which is `+`, which is `sh-basic-offset`.

In other words, the SMIE code is sometimes falling back to older values.

So, `dtrt-indent` should really set both variables (or defer to SMIE, as `smie-config-guess` changes the rule appropriately, but as you say, that issue already exists). I don't understand why sh-script.el's SMIE code uses `sh-indentation` and not `sh-basic-offset`.

Given that the aim is to make `dtrt-indent` defer to SMIE eventually, the best fix for now is probably to have it set both variables. I'll need to allow multiple variables per mode for that.

**Comment by rrthomas** [comment]
Since it's easier to implement SMIE support, I've done that instead, and reverted the variable to change to `sh-basic-offset` for Emacs < 24.4 (without SMIE).

**Comment by Apteryks** [comment]
The issue is now that `dtrt-indent-mode` doesn't infer the right setting for tabs vs spaces for `sh-mode`, as `smie` is not concerned with that :-(
