### ISSUE TITLE
1/253 relevant lines

### ISSUE THREAD

**Issue by tummychow** [jscheid/dtrt-indent#35]
dtrt-indent-diagnosis does not seem to like my bashrc. It reports only one relevant line out of the 253 lines in the file. https://github.com/tummychow/etc/blob/master/bash/.bashrc

I feel like this is clearly wrong, but I don't really know where to dig in. How do I debug dtrt-indent's analysis of this file?

**Comment by rrthomas** [comment]
Start with `dtrt-indent-diagnosis`.

**Comment by tummychow** [comment]
I did, that's how I got the result described above:
![maim-2018-02-02-09 09 22](https://user-images.githubusercontent.com/4285049/35745656-e051c582-07f8-11e8-8060-8d05fcaefefc.png)

**Comment by rrthomas** [comment]
Sorry, in that case you know about as much as I do, and the next thing is to look at the configuration about what is counted as relevant, and peruse the code. I've not found it that hard when looking at other oddities in the past.

**Comment by tummychow** [comment]
On closer inspection, I was unable to find any one regex of the [relevant lines syntax table](https://github.com/jscheid/dtrt-indent/blob/master/dtrt-indent.el#L272) that isolated the problem. It's a combination of multiple regexes that causes most of my bashrc to get ignored. I suspect it has something to do with the numerous escape codes used in the file (`\[\e[m\]`).

I don't think regexes are robust enough to solve this problem (ie ignoring multi-line statements and comments). I would prefer to remove this syntax table entirely and treat all nonempty indented lines as relevant. Is this change acceptable to you? If so, I am willing to write the patch myself. Let me know and I will submit a PR to that effect. If not, I understand, and this can be closed. Thanks.

**Comment by rrthomas** [comment]
I am inclined to agree with you. Although the `dtrt` in the mode's name implies some smarts, most of my changes have been to make it dumber, and that seems sensible here too, rather than have dtrt-indent-mode behave inscrutably with apparently-reasonable input. Your patch would therefore be most welcome.
