### ISSUE TITLE
dtrt-indent-try-set-offset doesn't set generic indent variables

### ISSUE THREAD

**Issue by hlissner** [jscheid/dtrt-indent#41]
On [lines 923-924](https://github.com/jscheid/dtrt-indent/blob/master/dtrt-indent.el#L923-L924) of `dtrt-indent-try-set-offset`, the following check

```elisp
(not (eq (symbol-value indent-offset-variable)
         best-indent-offset))
```

prevents other variables in `dtrt-indent-hook-generic-mapping-list` from being
set, even if they don't match the best guess.

i.e. I want `evil-shift-width` to be set to the best guess, but if the mode's
offset variable (say, `ruby-indent-level`) already matches the guess, it won't
bother.

I'm guessing this wasn't intentional, so I suggest either removing the check or 
checking if all indent-offset-variables match the best guess before short 
circuiting. (Shall I PR this?)

**Comment by rrthomas** [comment]
Thanks! I'd be happy with the simplest option (remove the check); please do submit a PR.
