### ISSUE TITLE
Fails to set js-indent-offset to 2 for this file

### ISSUE THREAD

**Issue by kaofelix** [jscheid/dtrt-indent#5]
I have this JavaScript file indented with 2 spaces. My default indent is 4 spaces. dtrt-indent fails to guess the correct level for this one and doesn't set the new indentation level at all. I've tried hard to edebug it and understand why this happens: it seems that inside `dtrt-indent--skip-to-end-of-match` it jumps from the line in my file that starts with `describe` to the end of the file (based on the syntax pairs, I suppose), and then it never goes back to account for any indented lines. That's my very superficial analysis, since I cannot understand how the algorithm really works or where to fix it.

Also, it works for some other JS files, so it seems to be something in particular with this structure.

```javascript 
'use strict';

describe('Controller: PlayerCtrl', function () {
  // load the controller's module
  beforeEach(module('angularTestApp'));

  var PlayerCtrl, scope;

  // Initialize the controller and a mock scope
  beforeEach(inject(function ($controller, $rootScope) {
    scope = $rootScope.$new();
    PlayerCtrl = $controller('MainCtrl', {
      $scope: scope
    });
  }));

  it('should default player score to a 1000', function () {
    expect().toBe(3);
  });
});
```

Cheers,
Kao

**Comment by rrthomas** [comment]
This works fine in current git master head (thanks to the introduction of Javascript-specific syntax, I think).
