### ISSUE TITLE
Issue with protobuf-mode

### ISSUE THREAD

**Issue by wberrier** [jscheid/dtrt-indent#54]
When running dtrt on a protocol buffers (cc-mode derived), dtrt sets up `standard-indent`, yet the protobuf-mode uses `c-basic-offset`.

What's the correct fix for this?

I tried adding `(protobuf-mode c-basic-offset)` to `dtrt-indent-hook-generic-mapping-list` but for some reason the `(boundp mode)` comes back false when checking for protobuf mode while in protobuf mode.

I'm pretty new at elisp, so I'm looking for some direction on a proper fix.  Or, maybe it's a configuration issue on my end?

**Comment by rrthomas** [comment]
You need to add your entry to `dtrt-indent-hook-mapping-list`, something like:

```
(protobuf-mode c/c++/java c-basic-offset)
```

The problem you're having is because the generic list is designed for variables, not modes. There is no `protobuf-mode` variable, so `boundp` will indeed return `nil`.

I've made a commit with the addition you need, and it seems to work; please could you confirm, and I can make a new release.

**Comment by wberrier** [comment]
Thanks for the help and response.  This indeed works:

```lisp
$ git diff
diff --git a/dtrt-indent.el b/dtrt-indent.el
index 8b665f3..97265ea 100644
--- a/dtrt-indent.el
+++ b/dtrt-indent.el
@@ -331,6 +331,7 @@ quote, for example.")
     (lua-mode        lua           lua-indent-level)     ; Lua
     (objc-mode       c/c++/java    c-basic-offset)       ; Objective C
     (php-mode        c/c++/java    c-basic-offset)       ; PHP
+    (protobuf-mode   c/c++/java    c-basic-offset)       ; Protocol Buffers
     (perl-mode       perl          perl-indent-level)    ; Perl
     (cperl-mode      perl          cperl-indent-level)   ; Perl
     (raku-mode       perl          raku-indent-offset)   ; Perl6/Raku
```

**Comment by rrthomas** [comment]
Thanks for confirming! Closing this issue, and I've tagged dtrt-indent version 1.3.
