### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by philippludwig** [jscheid/dtrt-indent#64]
The instructions state:

```
;; To install, M-x customize-group dtrt-indent-global, and turn on "Dtrt
;; Indent Global Mode".
```

However, the group `dtrt-indent-global` is not available for me. I guess I have to put the `*.el` files from the repository somewhere and load them somehow, but I am unsure what exactly the proper steps are.

**Comment by rrthomas** [comment]
Oh dear, the instructions were out of date; should be fixed now! If you agree, I can make a new release.

**Comment by philippludwig** [comment]
Thanks for the quick response! From a user’s perspective, this is exactly what I expected.

**Comment by rrthomas** [comment]
Thanks for confirming! I've tagged version 1.8, which should become a MELPA release shortly.
