### ISSUE TITLE
does this change my indent-tabs-mode?

### ISSUE THREAD

**Issue by rwa** [jscheid/dtrt-indent#7]
If so, I think that's a cardinal sin!

I started discovering tabs in my files recently, and noticed that I am now sometimes in indent-tabs-mode t, which is strange because I explicitly set this to nil with my programming mode hooks.

Use of this package is the only thing that has changed recently, and I do notice in the source that it seems to be mucking with indent-tabs-mode.

**Comment by rrthomas** [comment]
dtrt-indent does indeed alter indent-tabs-mode if it decides that the file it's looking at is tab-indented. If it's getting this wrong, feel free to reopen with an MWE.
