### ISSUE TITLE
Support `typescript-ts-base-mode` and thus `tsx-ts-mode`?

### ISSUE THREAD

**Issue by mekeor** [jscheid/dtrt-indent#77]
Currently, `dtrt-indent` supports `typescript-ts-mode`. But both `typescript-ts-mode` as well as `tsx-ts-mode` are derived from `typescript-base-ts-mode`. Is it intended that `tsx-ts-mode` and `typescript-base-ts-mode` are not supported by `dtrt-indent`?

**Comment by rrthomas** [comment]
This sounds like an oversight to me. Patch to rectify it most welcome!
