### ISSUE TITLE
Indent not being detected for a C++ header file

### ISSUE THREAD

**Issue by giogadi** [jscheid/dtrt-indent#8]
I'm having trouble getting dtrt-indent to detect the indent on the following header file:

https://gist.github.com/giogadi/7328741

I tried varying Minimum Relevant Lines and Minimum Superiority with no luck. What might be throwing off the detection in this file?

**Comment by rrthomas** [comment]
Closing, as `dtrt-indent-min-indent-superiority` no longer exists.
