### ISSUE TITLE
`dtrt-indent-set`

### ISSUE THREAD

**Issue by ramnes** [jscheid/dtrt-indent#82]
Hey there, thanks for the great mode!

I'm always wondering what command I need to type to change the indentation offset with the mode I'm on. What would you think of adding a `dtrt-indent-set` command that would prompt for an indentation offset, and work with all modes supported by `dtrt-indent-set` in the first place – thus acting as a central command for indentation?

**Comment by rrthomas** [comment]
I would certainly accept a PR for such a function, which I guess would use `dtrt-indent-hook-mapping-list` to find the variable to set for the current mode.
